USE [SIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [GMETOOL].[GMETeTBlockedRequest](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdChiamata] [bigint] NOT NULL,
	[Code] [varchar](72) NOT NULL,
	[Cause] [varchar](16) NOT NULL,
	[EventDate] [datetime] NOT NULL,
	[NotifierEventDate] [datetime] NOT NULL,
 CONSTRAINT [PK_GMETeTBlockedRequest_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 
GO

SET ANSI_PADDING ON
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_GMETeTBlockedRequest_IdChiamata_Code] ON [GMETOOL].[GMETeTBlockedRequest]
(
	[IdChiamata] ASC,
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO