USE [SIN]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [GMETOOL].[TeTGMEBlockedResponse](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IdChiamata] [bigint] NOT NULL,
	[IdPo] [varchar](72) NOT NULL,
	[MessageDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_TeTGMEBlockedResponse_Id] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [IDX_TeTGMEBlockedResponse_IdChiamata_IdPo] ON [GMETOOL].[TeTGMEBlockedResponse]
(
	[IdChiamata] ASC,
	[IdPo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
